### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by walmartwarlord** [MaxHilmbauer/vuetify-command-palette#2]
Hi, I installed it in a fresh Vite + Vuetify project but it's giving me a lot of errors. Is this project maintained?

**Comment by MaxHilmbauer** [comment]
I have now installed it like you did. The problem is that the vuetify-components in the command-palette can not be resolved. Until I fix this I have a workaround for it:

Navigate to your `vuetify.js` file and import the `components` and the `directives` in `createVuetify`
Your `vuetify.js` file should look like this afterwards:
```js
// vuetify.js
import "@mdi/font/css/materialdesignicons.css";
import "vuetify/styles";

import { createVuetify } from "vuetify";
import * as components from "vuetify/components";
import * as directives from "vuetify/directives";

export default createVuetify({
  components,
  directives,
  theme: {
    defaultTheme: "light",
  },
});
```

Hope it works for you!

**Comment by walmartwarlord** [comment]
Thank you!

Also, is this project related to [this](https://github.com/wobsoriano/v-command-palette) somehow?

**Comment by walmartwarlord** [comment]
Thank you!

Also, is this project related to [this](https://github.com/wobsoriano/v-command-palette) somehow?
